### PR TITLE
buildGoCache: fix for usage with `buildGoModule` and `proxyVendor = false`

### PR DESCRIPTION
**Pull request by katexochen**
cc @zimbatm

### CODE REVIEW

**Comment by zimbatm** [comment]
thanks!

**Comment by zimbatm** [comment]
Do you know what is going on with the darwin builds?

**Comment by katexochen** [comment]
- [aarch64-darwin.example/4](https://buildbot.numtide.com/#/builders/1015/builds/4)
  [aarch64-darwin.example-proxy-vendor/12](https://buildbot.numtide.com/#/builders/1012/builds/12)
  [aarch64-linux.example/4](https://buildbot.numtide.com/#/builders/1016/builds/4)
  [aarch64-linux.example-proxy-vendor/12](https://buildbot.numtide.com/#/builders/1013/builds/12)

  Failed with the following error:
  ```
  package github.com/intel/iaevents: build constraints exclude all Go files in /nix/store/niar6jqg3bkl21ql4icmlb4m0zp22x8p-go-cache/go-mod-cache/github.com/intel/iaevents@v1.1.0
  ```

  Which makes sense, as it is a library only targeting linux, using build directive `//go:build linux && amd64`.
   I'd assume the problem here is that the `impoted-packages` file was created on amd64-linux, so the list of packages includes those packages relevant to that arch. I'd assume that setting GOOS/GOARCH when running get-external-imports could solve this.  

- [aarch64-darwin.example-gomod2nix/12](https://buildbot.numtide.com/#/builders/997/builds/12)

  Fails with
  ```
  gomod2nix> cp: cannot stat '/private/tmp/nix-build-go-cache.drv-0/go-cache': Permission denied
  ```

  Unsure about this one, I'm not that familiar with gomod2nix. Would have to look deeper into the builder.

- [aarch64-darwin.example-no-cache/12](https://buildbot.numtide.com/#/builders/999/builds/12)
  Fails with

  ```
  telegraf> plugins/inputs/sql/drivers.go:9:2: cannot find module providing package github.com/microsoft/go-mssqldb: import lookup disabled by -mod=vendor
  ```
  This one is weird, as it is neither using the cache nor gomod2nix. Maybe there is a darwin specific verndorHash mismatch and the builder isn't noticing it due to caching? This was at least a problem in a run on this PR (the other failures are from main), but it is another test: [checks.aarch64-darwin.example/2](https://buildbot.numtide.com/#/builders/1015/builds/2)

**Comment by phanirithvij** [comment]
```
gomod2nix> cp: cannot stat '/private/tmp/nix-build-go-cache.drv-0/go-cache': Permission denied
```

This is happening at https://github.com/numtide/build-go-cache/blob/36f59cea5b4dec39c24b57381d15714cdac5578b/buildGoCache.nix#L69

Seems like in linux $TMPDIR is always /build but in macos it is `/private/tmp/something-different-per-derivation`.
So when the hook is run that TMPDIR needs to be used. 

Also when using `nix-shell .` with a derivation which utilises buildGoCache, the same issue occurs.

sent pr #12

**Pull request merged**
